= Jo

Highly inspired from https://github.com/google/ko[ko], a similar tool for Java using https://jbang.dev[jbang].

IMPORTANT: Under active development so lots change and nothing working perfectly now

== Pre-requisites

* https://www.docker.com/products/docker-desktop[Docker for Mac or Windows]
* https://kind.sigs.k8s.io/[kind] - to run your local Kubernetes cluster
* Java 11
* Maven 3.6.3+

NOTE: If you are using Docker for Windows, then https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows subsytem for Linux (WSL)] is recommended.

== Build jo

[source,bash]
----
git clone https://github.com/kameshsampath/jo
cd jo
export $PROJECT_HOME=`pwd` 
mvn clean install -DskipTests
----

== Start Kubernetes Cluster

[source,bash]
----
$PROJECT_HOME/bin/start-kind.sh
----

== Hello World (Kubernetes Example)

[source,bash]
----
cd $PROJECT_HOME
java -jar target/jo-runner.jar apply --file="$PWD/examples/kubernetes/deployment.yaml"
----

The command above should do the deployment of the jbang script github.com/kameshsampath/jo/examples/http/server.java as Kubernetes application.

Wait for the hello-world pod to come up:

[source,bash]
----
watch kubectl get pods 
----

Once the pods is up try creating the Service and Ingress to access it:

[source,bash]
----
cd $PROJECT_HOME
kubectl apply --file="$PROJECT_HOME/examples/kubernetes/service.yaml"
----

Now doing curl localhost/hello should show a response like **Hello World**

== Hello World (Knative Example)

[source,bash,subs="attributes+,macros+"]
----
cd $PROJECT_HOME
java -jar target/jo-runner.jar apply --file="$PWD/examples/knative/service.yaml"
----

The command above will create a Knative Service of the jbang script https://github.com/kameshsampath/jo/examples/http/server.java.

Wait for the greeter Knative service to come up:

[source,bash]
----
watch kubectl get pods
----

Once Knative service is up access the service using:

[source,bash]
----
SVC_URL=$(kubectl get ksvc greeter -ojsonpath="{.status.url}")
# the curl will return an Hello World response
curl $SVC_URL
----

== Powered by 

* https://quarkus.io[Quarkus]
* https://www.eclipse.org/jkube/[jkube]
