kind: Service
apiVersion: v1
metadata:
  name: jo-sb-helloworld-service
spec:
  selector:
   app: sb
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jo-sb-helloworld-service
spec:
  rules:
  - http:
      paths:
      - path: /hi
        backend:
          serviceName: jo-sb-helloworld-service
          servicePort: 8080