apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-jbang
spec:
  selector:
    matchLabels:
      src: jbang
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        src: jbang
        app: helloworld
    spec:
      containers:
        - name: hello-world
          image: jbang://github.com/kameshsampath/jo/examples/http/server
          imagePullPoicy: Always
          ports:
            - containerPort: 8080
