apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-spring-boot
spec:
  selector:
    matchLabels:
      src: spring-boot
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        src: spring-boot
        app: helloworld
    spec:
      containers:
        - name: hello-world
          image: java://github.com/kameshsampath/jo-sb-helloworld
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
