apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: hello-world
          image: jbang://github.com/kameshsampath/jo/examples/http/server
          ports:
            - containerPort: 8080
