apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-quarkus
spec:
  selector:
    matchLabels:
      src: quarkus
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        src: quarkus
        app: helloworld
    spec:
      containers:
        - name: hello-world
          image: quarkus://github.com/kameshsampath/jo-quarkus-helloworld
          imagePullPoicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
