apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: hello-world
          image: quarkus://github.com/kameshsampath/jo-quarkus-helloworld
          ports:
            - containerPort: 8080
